### ISSUE TITLE
Trigger Text Animations On Scroll

### ISSUE THREAD

**Issue by miah0x41** [SikandarJODD/svelte-animations#10]
Currently text animations such as the number ticker [1] are triggered on page load. Much like other animations such as BlurFade, have the option to be triggered by scrolling into view.

It would appear a similar implementation exists for React based on your Thank You list [2]

[1]: https://animation-svelte.vercel.app/magic/number-ticker
[2] https://ui.indie-starter.dev/docs/text-animation#letters-pull-up

Edit: added additional reference.

**Comment by SikandarJODD** [comment]
yeep i will try to add in-view for components good idea

**Comment by miah0x41** [comment]
Much appreciated, thanks for your hard work!

**Comment by SikandarJODD** [comment]
Solved : Added refresh button 
![image](https://github.com/user-attachments/assets/b0ebc576-27fb-4023-91e7-ef408de203d7)

well i added 2 more components from Magic UI 
1. **Flickering Grid** :  https://animation-svelte.vercel.app/magic/flickering-grid
2. **Sparkles Text**  : https://animation-svelte.vercel.app/magic/sparkles-text

**Comment by SikandarJODD** [comment]
sorry i know it took lot of time..for such small change

**Comment by miah0x41** [comment]
Please do not apologise, we appreciate your unpaid labour. 


I realised that my original request wasn't very clear or perhaps I haven't understood the change you made. 


What I was after, when I use the component (the Number Ticker) it should start counting when it comes into view on a long page. I can't see the use of inView in the code. 

I'll try it out to see if that's what happens.

Thanks.
