### ISSUE TITLE
Standard components

### ISSUE THREAD

**Issue by MathiasWP** [SikandarJODD/svelte-animations#14]
This library is amazing, probably the coolest Svelte library i've ever seen. Do you have any plans to support the most basic app-components like Button, Menu, Dialog/Modal/Prompt, Textarea, Checkbox etc?

**Comment by SikandarJODD** [comment]
Components are focused on Magic UI, Indie UI..and many more right now working on Aceternity UI ...let see in future ...
whole point is : to build  animation, good looking components in svelte..
you will find the standard components on shadcn UI

**Comment by SikandarJODD** [comment]
do you have any recomendation related to standard components ?
