### ISSUE TITLE
Add Marquee Component

### ISSUE THREAD

**Issue by kakajuro** [SikandarJODD/svelte-animations#22]
Hi, this library is awesome so far. I'd love to see a Marquee component similar to the one in [Magic UI](https://magicui.design/docs/components/marquee). Keep up the great work

**Comment by SikandarJODD** [comment]
Chekout : [Marquee](https://animation-svelte.vercel.app/magic/marquee) 
I already build this ..would add more examples soon

**Comment by kakajuro** [comment]
Oh! I guess I missed it, sorry about that. Thanks anyways

**Comment by SikandarJODD** [comment]
yeep if you need any other let me know..i will work on it
