### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by chanmathew** [SikandarJODD/svelte-animations#4]
Hi there, thanks for the great lib!

I noticed that the documentation that mentions the TailwindCSS part seems to be buggy and persist across different page loads.

For example if you visit the Marque page, then visit the Orbit page, it still shows the Tailwind config for the Marquee page.

**Comment by SikandarJODD** [comment]
thanks i will update it

**Comment by SikandarJODD** [comment]
Update Complete
