### ISSUE TITLE
Website light mode color bug

### ISSUE THREAD

**Issue by Mingx94** [SikandarJODD/svelte-animations#5]
Issue link: https://animation-svelte.vercel.app/examples

I'm currently in light mode and the sidebar color appears to be not quite right. 

Wide Mode
<img width="123" alt="截圖 2024-07-10 14 01 59" src="https://github.com/SikandarJODD/svelte-animations/assets/37038363/9cfb1902-cc55-43c4-a5db-ee60e28566f6">

Under 1024
<img width="119" alt="截圖 2024-07-10 14 02 57" src="https://github.com/SikandarJODD/svelte-animations/assets/37038363/262a4da8-e7e3-44f8-8540-0c7a1b9b6a8e">

**Comment by SikandarJODD** [comment]
yeep working on it

**Comment by SikandarJODD** [comment]
yeep the issue is solved
