### ISSUE TITLE
Add: Animated Circular Progress Bar

### ISSUE THREAD

**Issue by bn-l** [SikandarJODD/svelte-animations#8]
Hi there, great work on this one. Any plans to add the circular progress bar?:

https://magicui.design/docs/components/animated-circular-progress-bar

**Comment by shyakadavis** [comment]
Hi;

Worked on something similar-ish. Leaving it here for consideration/inspiration, but it needs more work if it is to reach the level from MagicUI.

- https://geist.shyakadavis.me/gauge
- https://github.com/shyakadavis/geist/blob/main/src/lib/components/ui/gauge/gauge.svelte

Cheers.

**Comment by bn-l** [comment]
Thanks

> Hi;
> 
> Worked on something similar-ish. Leaving it here for consideration/inspiration, but it needs more work if it is to reach the level from MagicUI.
> 
> * https://geist.shyakadavis.me/gauge
> * https://github.com/shyakadavis/geist/blob/main/src/lib/components/ui/gauge/gauge.svelte
> 
> Cheers.

Thanks for the link. Interesting to see Geist being implemented for svelte as well!
![Screenshot 2024-08-08 001555](https://github.com/user-attachments/assets/d93b2297-7b9b-4a1a-82c3-77055af1419a)



It's arguably small but what I love about magic's implementation is these little breaks in the circle. Something about it is very satisfying.

**Comment by shyakadavis** [comment]
Yes indeed. It eludes me still (https://github.com/shyakadavis/geist/issues/34), and I am yet to figure out how to add those gaps between arcs. 😅

**Comment by SikandarJODD** [comment]
> Hi there, great work on this one. Any plans to add the circular progress bar?:
> 
> https://magicui.design/docs/components/animated-circular-progress-bar

Added : Animated Circular Progress bar 
Component : https://animation-svelte.vercel.app/magic/circular-progress-bar

**Comment by SikandarJODD** [comment]
![image](https://github.com/user-attachments/assets/11e6dda6-2f0c-40dc-aabc-9561c3b66b0d)

**Comment by SikandarJODD** [comment]
i tried using spring, tweened to increment the value of ```value```
you can try out different methods to increment the value

**Comment by bn-l** [comment]
Looks perfect
